
version: "2.2"
services:
  jobmanager:
    image: flinkcdc:latest
    security_opt:
      - seccomp=unconfined
    ports:
      - "127.0.0.1:8082:8081"
    command: "jobmanager"
    volumes:
      - /home/flink/flinkcdc/upload:/opt/flink/upload:Z
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        web.upload.dir: /opt/flink/upload
        jobmanager.memory.process.size: 4800m
  taskmanager:
    image: flinkcdc:latest
    security_opt:
      - seccomp=unconfined
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10

  sql-client:
    image: flinkcdc:latest
    command: bin/sql-client.sh
    security_opt:
      - seccomp=unconfined
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
